# Generated by Django 2.2.12 on 2022-12-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20221228_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
    ]
