# Generated by Django 4.1.4 on 2023-01-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_bid_alter_bid_bid_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
    ]
