# Generated by Django 3.2.12 on 2023-04-04 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
