# Generated by Django 4.1.7 on 2023-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='media/itikaf.png', upload_to='media/'),
        ),
    ]
