# Generated by Django 4.1.7 on 2023-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_imageurl_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='media/itikaf.png', upload_to='media'),
        ),
    ]
